remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Hur man skapar dual boot med Kubuntu och Windows
description: För elever på IT-inriktningen @tcstenungsund  

show_downloads: false
